# ─── Andromeda v45.2.0 — Dockerfile ─────────────────────────────────────────
#
# Multi-stage build:
#   Stage 1 (builder): Install deps, build TypeScript + Vite frontend
#   Stage 2 (runner):  Minimal production image with only dist/ and node_modules
#
# Fix history:
#   v45.2.0  — pnpm@11.5.2 → pnpm@11.9.0 to match lockfile generated by pnpm 11.9.0.
#              Fixes ERR_PNPM_OUTDATED_LOCKFILE: typescript specifier mismatch.
#              The Dockerfile pnpm version MUST always match `pnpm --version` on the
#              machine that committed pnpm-lock.yaml.
#   v12.8.1  — Copy .pnpmfile.cjs before pnpm install (fixes ERR_PNPM_LOCKFILE_CONFIG_MISMATCH).
#              Fix Express v5 wildcard routes: app.use("*") → app.use("/{*path}") in vite.ts.
#   v9.16.3b — pnpm@10.15.1 → pnpm@11.5.2 to match lockfileVersion: '9.0'.
#              The pnpm-lock.yaml is generated by pnpm 11. pnpm 10 cannot read
#              a pnpm-11 lockfile and exits with code 254. The Dockerfile pnpm
#              version MUST match whatever generated the committed lockfile.
#              Also: copy patches/ dir (required by pnpm-workspace.yaml patch).
#   v9.16.3  — pnpm@11.3.0 → pnpm@10.15.1 (incorrect, now reverted).
#   v9.16.2  — Fix CMD path: dist/server/index.js → dist/_core/index.js.
#
# Usage:
#   docker build -t andromeda:latest .
#   docker run -p 3000:3000 --env-file .env.local andromeda:latest
#
# Or with docker-compose:
#   docker-compose up
# ─────────────────────────────────────────────────────────────────────────────

# ── Stage 1: Builder ──────────────────────────────────────────────────────────
FROM node:22-alpine AS builder

# Install pnpm matching the version that generated pnpm-lock.yaml (pnpm 11.9.0)
RUN corepack enable && corepack prepare pnpm@11.9.0 --activate

# Native build tools: better-sqlite3 needs python3/make/g++; canvas needs cairo stack
RUN apk add --no-cache python3 make g++ cairo-dev pango-dev jpeg-dev giflib-dev

WORKDIR /app

# Copy dependency manifests first (layer cache optimization)
COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
# Copy .pnpmfile.cjs BEFORE pnpm install — this hook overrides the qs version.
# The lockfile checksum was computed with this hook active; omitting it causes
# ERR_PNPM_LOCKFILE_CONFIG_MISMATCH and a --frozen-lockfile failure.
COPY .pnpmfile.cjs ./
# Copy patches directory (required by pnpm-workspace.yaml patchedDependencies)
COPY patches/ ./patches/

# Two-step install: skip postinstall scripts first, then rebuild native addons.
# This prevents canvas/better-sqlite3 from failing mid-install.
RUN pnpm install --frozen-lockfile --ignore-scripts
RUN pnpm rebuild

# Copy source
COPY . .

# Build TypeScript server + Vite frontend
RUN pnpm run build

# ── Stage 2: Runner ───────────────────────────────────────────────────────────
FROM node:22-alpine AS runner

# Install pnpm matching the lockfile version (pnpm 11.9.0)
RUN corepack enable && corepack prepare pnpm@11.9.0 --activate

# Runtime native deps: better-sqlite3 + canvas + git (for RSI patch apply)
RUN apk add --no-cache python3 make g++ git cairo-dev pango-dev jpeg-dev giflib-dev

# Create non-root user for security
RUN addgroup --system --gid 1001 andromeda && \
    adduser --system --uid 1001 --ingroup andromeda andromeda

WORKDIR /app

# Copy built artifacts from builder stage
COPY --from=builder --chown=andromeda:andromeda /app/dist ./dist
COPY --from=builder --chown=andromeda:andromeda /app/package.json ./package.json
COPY --from=builder --chown=andromeda:andromeda /app/pnpm-lock.yaml ./
COPY --from=builder --chown=andromeda:andromeda /app/pnpm-workspace.yaml ./
COPY --from=builder --chown=andromeda:andromeda /app/.pnpmfile.cjs ./
COPY --from=builder --chown=andromeda:andromeda /app/patches/ ./patches/

# Install production dependencies only (two-step for native addons)
RUN pnpm install --frozen-lockfile --prod --ignore-scripts
RUN pnpm rebuild

# Create data directories for persistent storage (SQLite, episodic memory, eval baseline, RSI state)
RUN mkdir -p /app/data /app/.data && chown -R andromeda:andromeda /app/data /app/.data

# Create workspace directory for file operations
RUN mkdir -p /app/workspace && chown andromeda:andromeda /app/workspace

# Switch to non-root user
USER andromeda

# Expose the default port
EXPOSE 3000

# Health check — uses the /health endpoint added in v6.04
HEALTHCHECK --interval=30s --timeout=10s --start-period=30s --retries=3 \
  CMD wget -qO- http://localhost:3000/health || exit 1

# Environment defaults (override with --env-file or -e flags)
ENV NODE_ENV=production \
    PORT=3000

# Start the production server
CMD ["node", "dist/_core/index.js"]
