packages:
  - '.'

allowBuilds:
  '@tailwindcss/oxide': true
  esbuild: true
onlyBuiltDependencies:
  - esbuild
  - '@tailwindcss/oxide'
patchedDependencies:
  wouter@3.7.1: patches/wouter@3.7.1.patch
