/**
 * cli/commands/config.ts — v2.0.0
 * `andromeda config` — interactive configuration wizard for .env.local setup.
 */
import { Command } from "commander";
import * as readline from "readline";
import { existsSync, readFileSync, writeFileSync } from "fs";
import { resolve } from "path";
import chalk from "chalk";
import { printBanner, printSuccess, printError, printInfo, printWarning, printDim } from "../ui/banner.js";

const ROOT = resolve(import.meta.dirname, "../..");

interface ConfigField {
  key: string;
  label: string;
  description: string;
  required: boolean;
  secret: boolean;
  default?: string;
  validate?: (v: string) => string | null;
}

const CONFIG_FIELDS: ConfigField[] = [
  {
    key: "OPENAI_API_KEY",
    label: "OpenAI API Key",
    description: "Used for GPT-4o proposals and eval scoring",
    required: false,
    secret: true,
    validate: (v) => v && !v.startsWith("sk-") ? "OpenAI keys start with sk-" : null,
  },
  {
    key: "ANTHROPIC_API_KEY",
    label: "Anthropic API Key",
    description: "Used for Claude-based proposals",
    required: false,
    secret: true,
    validate: (v) => v && !v.startsWith("sk-ant-") ? "Anthropic keys start with sk-ant-" : null,
  },
  {
    key: "OPENROUTER_API_KEY",
    label: "OpenRouter API Key",
    description: "Access 200+ models via a single key",
    required: false,
    secret: true,
  },
  {
    key: "OLLAMA_BASE_URL",
    label: "Ollama Base URL",
    description: "Local Ollama instance for free inference",
    required: false,
    secret: false,
    default: "http://localhost:11434",
  },
  {
    key: "GITHUB_TOKEN",
    label: "GitHub Token",
    description: "Required for RSI to commit improvements",
    required: false,
    secret: true,
    validate: (v) => v && !v.startsWith("ghp_") && !v.startsWith("github_pat_") ? "GitHub tokens start with ghp_ or github_pat_" : null,
  },
  {
    key: "DATABASE_URL",
    label: "Database URL",
    description: "PostgreSQL connection string (optional — uses SQLite by default)",
    required: false,
    secret: true,
    default: "",
  },
  {
    key: "RSI_ENABLED",
    label: "Enable RSI Daemon",
    description: "Auto-improvement loop (true/false)",
    required: false,
    secret: false,
    default: "true",
    validate: (v) => !["true", "false"].includes(v) ? "Must be true or false" : null,
  },
  {
    key: "RSI_INTERVAL_MINUTES",
    label: "RSI Interval (minutes)",
    description: "How often to run improvement cycles",
    required: false,
    secret: false,
    default: "30",
    validate: (v) => isNaN(parseInt(v, 10)) ? "Must be a number" : null,
  },
];

function readEnv(path: string): Record<string, string> {
  if (!existsSync(path)) return {};
  const content = readFileSync(path, "utf8");
  const result: Record<string, string> = {};
  for (const line of content.split("\n")) {
    const m = line.match(/^\s*([A-Z_]+)\s*=\s*(.+)$/);
    if (m) result[m[1]] = m[2].trim();
  }
  return result;
}

function writeEnv(path: string, values: Record<string, string>): void {
  const lines = [
    "# Andromeda Configuration",
    "# Generated by `andromeda config`",
    "# DO NOT commit this file to version control",
    "",
  ];
  for (const [key, value] of Object.entries(values)) {
    if (value) lines.push(`${key}=${value}`);
  }
  writeFileSync(path, lines.join("\n") + "\n");
}

async function prompt(rl: readline.Interface, question: string, secret = false): Promise<string> {
  return new Promise((resolve) => {
    if (secret) {
      // Mask input
      process.stdout.write(question);
      let input = "";
      process.stdin.setRawMode?.(true);
      process.stdin.resume();
      process.stdin.setEncoding("utf8");
      const handler = (char: string) => {
        if (char === "\n" || char === "\r" || char === "\u0004") {
          process.stdin.setRawMode?.(false);
          process.stdin.pause();
          process.stdin.removeListener("data", handler);
          process.stdout.write("\n");
          resolve(input);
        } else if (char === "\u0003") {
          process.exit(0);
        } else if (char === "\u007f") {
          if (input.length > 0) {
            input = input.slice(0, -1);
            process.stdout.write("\b \b");
          }
        } else {
          input += char;
          process.stdout.write("*");
        }
      };
      process.stdin.on("data", handler);
    } else {
      rl.question(question, resolve);
    }
  });
}

export function configCommand(): Command {
  const cmd = new Command("config");
  cmd
    .description("Interactive configuration wizard for .env.local")
    .option("--show", "Show current configuration (masked)")
    .option("--reset", "Reset to defaults")
    .action(async (opts) => {
      console.log(printBanner());

      const envPath = resolve(ROOT, ".env.local");
      const current = readEnv(envPath);

      if (opts.show) {
        console.log(chalk.bold("  Current Configuration:\n"));
        for (const field of CONFIG_FIELDS) {
          const val = current[field.key];
          if (val) {
            const display = field.secret
              ? val.slice(0, 8) + "…" + val.slice(-4)
              : val;
            console.log(`  ${chalk.cyan(field.key.padEnd(30))} ${chalk.white(display)}`);
          } else {
            console.log(`  ${chalk.dim(field.key.padEnd(30))} ${chalk.dim("(not set)")}`);
          }
        }
        console.log("");
        return;
      }

      printInfo("This wizard will help you configure Andromeda.");
      printDim("Press Enter to keep the current value. Ctrl+C to cancel.");
      console.log("");

      const rl = readline.createInterface({ input: process.stdin, output: process.stdout });
      const newValues: Record<string, string> = { ...current };

      for (const field of CONFIG_FIELDS) {
        const currentVal = current[field.key] ?? field.default ?? "";
        const displayCurrent = currentVal
          ? field.secret
            ? chalk.dim(`[${currentVal.slice(0, 4)}…]`)
            : chalk.dim(`[${currentVal}]`)
          : chalk.dim("[empty]");

        console.log(`  ${chalk.bold(field.label)} ${displayCurrent}`);
        console.log(`  ${chalk.dim(field.description)}`);

        const answer = await prompt(
          rl,
          `  ${chalk.cyan("›")} `,
          field.secret
        );

        const val = answer.trim() || currentVal;

        if (val && field.validate) {
          const err = field.validate(val);
          if (err) printWarning(err);
        }

        if (val) newValues[field.key] = val;
        console.log("");
      }

      rl.close();

      writeEnv(envPath, newValues);
      printSuccess(`.env.local saved to ${envPath}`);
      printInfo("Run `andromeda doctor` to verify your configuration.");
    });

  return cmd;
}
