/**
 * apiClientGenerator.ts — v51.0.0
 *
 * Generates typed TypeScript API client code from parsed API documentation.
 * Produces fetch-based client modules with full type safety.
 */

import type { ParsedApiDoc, ApiEndpoint } from "./apiDocumentationParser.js";

export interface GeneratedClient {
  filename: string;
  code: string;
  endpointCount: number;
  generatedAt: number;
}

export function generateClient(doc: ParsedApiDoc, clientName = "ApiClient"): GeneratedClient {
  const lines: string[] = [];

  lines.push(`/**`);
  lines.push(` * ${clientName} — Auto-generated from "${doc.title}" v${doc.version}`);
  lines.push(` * Generated by Andromeda apiClientGenerator`);
  lines.push(` */`);
  lines.push(``);
  lines.push(`const BASE_URL = "${doc.baseUrl}";`);
  lines.push(``);
  lines.push(`async function request<T>(method: string, path: string, body?: unknown, headers?: Record<string, string>): Promise<T> {`);
  lines.push(`  const res = await fetch(\`\${BASE_URL}\${path}\`, {`);
  lines.push(`    method,`);
  lines.push(`    headers: { "Content-Type": "application/json", ...headers },`);
  lines.push(`    body: body ? JSON.stringify(body) : undefined,`);
  lines.push(`  });`);
  lines.push(`  if (!res.ok) throw new Error(\`API error \${res.status}: \${await res.text()}\`);`);
  lines.push(`  return res.json() as Promise<T>;`);
  lines.push(`}`);
  lines.push(``);
  lines.push(`export const ${clientName} = {`);

  for (const endpoint of doc.endpoints) {
    const fnName = endpointToFunctionName(endpoint);
    const pathParams = endpoint.parameters.filter(p => p.in === "path");
    const queryParams = endpoint.parameters.filter(p => p.in === "query");
    const hasBody = ["POST", "PUT", "PATCH"].includes(endpoint.method);

    const paramList: string[] = [];
    for (const p of pathParams) paramList.push(`${p.name}: string`);
    for (const p of queryParams) paramList.push(`${p.name}${p.required ? "" : "?"}: string`);
    if (hasBody) paramList.push(`body?: Record<string, unknown>`);

    const pathExpr = endpoint.path.replace(/{(\w+)}/g, "${$1}");
    const queryStr = queryParams.length > 0
      ? `\n    const qs = new URLSearchParams(Object.fromEntries(Object.entries({ ${queryParams.map(p => p.name).join(", ")} }).filter(([,v]) => v !== undefined))).toString();\n    const url = \`${pathExpr}\${qs ? "?" + qs : ""}\`;`
      : `\n    const url = \`${pathExpr}\`;`;

    lines.push(`  /** ${endpoint.summary || endpoint.path} */`);
    lines.push(`  async ${fnName}(${paramList.join(", ")}): Promise<unknown> {${queryStr}`);
    lines.push(`    return request("${endpoint.method}", url${hasBody ? ", body" : ""});`);
    lines.push(`  },`);
    lines.push(``);
  }

  lines.push(`};`);

  return {
    filename: `${clientName.toLowerCase()}.generated.ts`,
    code: lines.join("\n"),
    endpointCount: doc.endpoints.length,
    generatedAt: Date.now(),
  };
}

function endpointToFunctionName(endpoint: ApiEndpoint): string {
  const method = endpoint.method.toLowerCase();
  const pathParts = endpoint.path
    .replace(/\{[^}]+\}/g, "By$&")
    .replace(/[{}]/g, "")
    .split("/")
    .filter(Boolean)
    .map(p => p.charAt(0).toUpperCase() + p.slice(1));
  return `${method}${pathParts.join("")}`;
}

export function generateClientFromEndpoints(endpoints: ApiEndpoint[], baseUrl: string, clientName = "ApiClient"): GeneratedClient {
  return generateClient({ title: clientName, version: "1.0.0", baseUrl, endpoints, format: "openapi" }, clientName);
}
