import fs from "fs";
import path from "path";

const DOCS_DIR = path.join(process.cwd(), "docs");
const CHANGELOG_PATH = path.join(process.cwd(), "CHANGELOG.md");

export interface DocUpdate {
  filePath: string;
  summary: string;
  timestamp: number;
}

export function initDocSynthesizer(): void {
  if (!fs.existsSync(DOCS_DIR)) {
    fs.mkdirSync(DOCS_DIR, { recursive: true });
  }
  if (!fs.existsSync(CHANGELOG_PATH)) {
    fs.writeFileSync(CHANGELOG_PATH, "# Andromeda RSI Changelog\n\n");
  }
}

/**
 * Appends a successful RSI change to the autonomous changelog.
 */
export function recordDocUpdate(filePath: string, summary: string): void {
  const entry = `- **${new Date().toISOString()}** [${path.basename(filePath)}]: ${summary}\n`;
  fs.appendFileSync(CHANGELOG_PATH, entry);
}

/**
 * Very basic JSDoc synthesizer - in a real implementation this would use the LLM
 * to generate proper JSDoc blocks for exported functions.
 */
export function synthesizeJsDoc(content: string): string {
  // Simple heuristic: if it has an export function without a docblock, add a generic one
  const lines = content.split("\n");
  const result: string[] = [];
  
  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    if (line.startsWith("export function") || line.startsWith("export async function")) {
      // Check if previous line is a docblock end
      if (i === 0 || !lines[i-1].trim().endsWith("*/")) {
        const funcNameMatch = line.match(/function\s+([a-zA-Z0-9_]+)/);
        const funcName = funcNameMatch ? funcNameMatch[1] : "Function";
        result.push(`/**\n * Autogenerated JSDoc for ${funcName}\n */`);
      }
    }
    result.push(line);
  }
  
  return result.join("\n");
}
