/**
 * autonomousGoalGenerator.ts — v5.33
 *
 * Autonomous Goal Generation Module.
 *
 * Enables Andromeda to identify its own weaknesses and create improvement
 * goals WITHOUT human prompting. This is the key module that transforms
 * Andromeda from a tool into an agent.
 *
 * Goal sources:
 * 1. Self-model capability gaps
 * 2. Error log patterns
 * 3. Performance metric degradation
 * 4. Test coverage gaps
 * 5. Dependency health
 * 6. Cross-session learning patterns
 *
 * Safety:
 * - Goals are generated but NOT auto-applied by default
 * - Each goal has a confidence score
 * - Goals targeting protected modules are blocked (via recursiveGoals guard)
 * - Maximum 5 auto-generated goals per cycle
 */

import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

// ─── Types ─────────────────────────────────────────────────────────────────────

export interface GeneratedGoal {
  id: string;
  title: string;
  description: string;
  source: "capability_gap" | "error_pattern" | "performance" | "coverage" | "dependency" | "learning";
  priority: number;       // 1-10
  confidence: number;     // 0-1
  estimatedEffort: "low" | "medium" | "high";
  targetFiles: string[];
  autoGenerated: true;
  createdAt: number;
  status: "proposed" | "approved" | "in_progress" | "completed" | "rejected";
  rationale: string;
}

export interface GoalGenerationResult {
  goals: GeneratedGoal[];
  analysisTime: number;
  sourcesAnalyzed: string[];
  skipped: string[];
}

// ─── Storage ───────────────────────────────────────────────────────────────────

const MAX_GOALS_PER_CYCLE = 5;
const MAX_STORED_GOALS = 50;
let generatedGoals: GeneratedGoal[] = [];
let lastGenerationTime = 0;
const COOLDOWN_MS = 10 * 60 * 1000; // 10 minutes between generations

function getGoalsPath(): string {
  const serverDir = path.dirname(fileURLToPath(import.meta.url));
  const workspaceDir = path.resolve(serverDir, "..", "workspace");
  if (!fs.existsSync(workspaceDir)) fs.mkdirSync(workspaceDir, { recursive: true });
  return path.join(workspaceDir, ".andromeda_auto_goals.json");
}

function loadGoals(): void {
  try {
    const goalsPath = getGoalsPath();
    if (fs.existsSync(goalsPath)) {
      generatedGoals = JSON.parse(fs.readFileSync(goalsPath, "utf-8"));
    }
  } catch { /* start fresh */ }
}

function saveGoals(): void {
  try {
    // Keep only the most recent goals
    if (generatedGoals.length > MAX_STORED_GOALS) {
      generatedGoals = generatedGoals.slice(-MAX_STORED_GOALS);
    }
    const goalsPath = getGoalsPath();
    fs.writeFileSync(goalsPath, JSON.stringify(generatedGoals, null, 2));
  } catch (err) {
    console.warn(`[AutoGoalGen] Failed to save goals: ${(err as Error).message}`);
  }
}

function generateId(): string {
  return `agoal_${Date.now()}_${Math.random().toString(36).slice(2, 8)}`;
}

function createGoal(params: {
  title: string;
  description: string;
  source: GeneratedGoal['source'];
  priority: number;
  confidence: number;
  estimatedEffort: GeneratedGoal['estimatedEffort'];
  targetFiles?: string[];
  rationale: string;
}): GeneratedGoal {
  return {
    id: generateId(),
    title: params.title,
    description: params.description,
    source: params.source,
    priority: params.priority,
    confidence: params.confidence,
    estimatedEffort: params.estimatedEffort,
    targetFiles: params.targetFiles || [],
    autoGenerated: true,
    createdAt: Date.now(),
    status: 'proposed',
    rationale: params.rationale,
  };
}

// ─── Goal Source Analyzers ─────────────────────────────────────────────────────

/**
 * Analyze self-model for capability gaps.
 */
async function analyzeCapabilityGaps(): Promise<GeneratedGoal[]> {
  const goals: GeneratedGoal[] = [];

  try {
    const { getSelfModel } = await import("./selfModel");
    const model = getSelfModel();

    if (model && model.capabilities) {
      const caps = Array.isArray(model.capabilities) ? model.capabilities : Object.values(model.capabilities);
      for (const cap of caps) {
        const c = cap as any;
        if (c.enabled === false || c.status === "degraded" || c.status === "disabled") {
          goals.push(createGoal({
            title: `Enable/fix ${c.name || "unknown"} capability`,
            description: `Capability '${c.name || "unknown"}' is ${c.status || "disabled"}. Investigate and restore.`,
            source: "capability_gap",
            priority: 8,
            confidence: 0.9,
            estimatedEffort: "medium",
            targetFiles: c.module ? [`server/${c.module}.ts`] : [],
            rationale: `Self-model reports capability as ${c.status || "disabled"}`,
          }));
        }
      }
    }
  } catch {
    // selfModel not available
  }

  return goals;
}

/**
 * Analyze error patterns from selfMonitor.
 */
async function analyzeErrorPatterns(): Promise<GeneratedGoal[]> {
  const goals: GeneratedGoal[] = [];

  try {
    const { getHealthReport } = await import("./selfMonitor");
    const report = getHealthReport();

    if (report && report.metrics) {
      const metrics = report.metrics as Record<string, any>;

      // High error rate
      if (metrics.error_rate && metrics.error_rate.current > 0.1) {
        goals.push(createGoal({
          title: "Reduce error rate below 10%",
          description: `Current error rate is ${(metrics.error_rate.current * 100).toFixed(1)}%. Analyze recent errors and implement fixes.`,
          source: "error_pattern",
          priority: 9,
          confidence: 0.85,
          estimatedEffort: "medium",
          rationale: `Error rate ${(metrics.error_rate.current * 100).toFixed(1)}% exceeds 10% threshold`,
        }));
      }

      // High truncation rate
      if (metrics.truncation_rate && metrics.truncation_rate.current > 0.15) {
        goals.push(createGoal({
          title: "Reduce truncation rate below 15%",
          description: `Current truncation rate is ${(metrics.truncation_rate.current * 100).toFixed(1)}%. Optimize context management and token budgets.`,
          source: "error_pattern",
          priority: 9,
          confidence: 0.9,
          estimatedEffort: "high",
          targetFiles: ["server/tieredContextManager.ts", "server/tokenBudgetManager.ts"],
          rationale: `Truncation rate ${(metrics.truncation_rate.current * 100).toFixed(1)}% exceeds 15% threshold`,
        }));
      }

      // High latency
      if (metrics.response_latency && metrics.response_latency.current > 20000) {
        goals.push(createGoal({
          title: "Reduce response latency below 20s",
          description: `Average response latency is ${(metrics.response_latency.current / 1000).toFixed(1)}s. Optimize LLM calls and caching.`,
          source: "performance",
          priority: 7,
          confidence: 0.8,
          estimatedEffort: "high",
          targetFiles: ["server/ai.ts", "server/_core/llm.ts"],
          rationale: `Latency ${(metrics.response_latency.current / 1000).toFixed(1)}s exceeds 20s threshold`,
        }));
      }

      // High tool failure rate
      if (metrics.tool_failure_rate && metrics.tool_failure_rate.current > 0.15) {
        goals.push(createGoal({
          title: "Reduce tool failure rate below 15%",
          description: `Tool failure rate is ${(metrics.tool_failure_rate.current * 100).toFixed(1)}%. Investigate failing tools and add error handling.`,
          source: "error_pattern",
          priority: 8,
          confidence: 0.85,
          estimatedEffort: "medium",
          rationale: `Tool failure rate ${(metrics.tool_failure_rate.current * 100).toFixed(1)}% exceeds 15% threshold`,
        }));
      }
    }
  } catch {
    // selfMonitor not available
  }

  return goals;
}

/**
 * Analyze cross-session learnings for improvement opportunities.
 */
async function analyzeLearningPatterns(): Promise<GeneratedGoal[]> {
  const goals: GeneratedGoal[] = [];

  try {
    const { queryUnifiedKnowledge } = await import("./unifiedKnowledge");
    const errorLearnings = await queryUnifiedKnowledge({
      query: "error fix improvement bug",
      sources: ["systemMemory", "selfKnowledgeBase"],
      limit: 10,
      minRelevance: 0.3,
    });

    // If we have many error-related learnings, suggest a systematic review
    if (errorLearnings.entries.length >= 5) {
      goals.push({
        id: generateId(),
        title: "Systematic review of recurring error patterns",
        description: `Found ${errorLearnings.entries.length} error-related learnings across sessions. A systematic review could identify root causes.`,
        source: "learning",
        priority: 6,
        confidence: 0.7,
        estimatedEffort: "medium",
        targetFiles: [],
        autoGenerated: true,
        createdAt: Date.now(),
        status: "proposed",
        rationale: `${errorLearnings.entries.length} error-related learnings suggest recurring issues`,
      });
    }
  } catch {
    // unifiedKnowledge not available
  }

  return goals;
}

// ─── Main Generation Function ──────────────────────────────────────────────────

/**
 * Generate improvement goals autonomously.
 * Analyzes multiple sources and creates prioritized goals.
 */
export async function generateImprovementGoals(): Promise<GoalGenerationResult> {
  const startTime = Date.now();

  // Cooldown check
  if (Date.now() - lastGenerationTime < COOLDOWN_MS) {
    return {
      goals: [],
      analysisTime: 0,
      sourcesAnalyzed: [],
      skipped: ["Cooldown active"],
    };
  }

  loadGoals();
  lastGenerationTime = Date.now();

  const sourcesAnalyzed: string[] = [];
  const skipped: string[] = [];
  const newGoals: GeneratedGoal[] = [];

  // ── 1. Capability gaps ──
  try {
    const capGoals = await analyzeCapabilityGaps();
    newGoals.push(...capGoals);
    sourcesAnalyzed.push("capability_gaps");
  } catch {
    skipped.push("capability_gaps");
  }

  // ── 2. Error patterns ──
  try {
    const errorGoals = await analyzeErrorPatterns();
    newGoals.push(...errorGoals);
    sourcesAnalyzed.push("error_patterns");
  } catch {
    skipped.push("error_patterns");
  }

  // ── 3. Learning patterns ──
  try {
    const learningGoals = await analyzeLearningPatterns();
    newGoals.push(...learningGoals);
    sourcesAnalyzed.push("learning_patterns");
  } catch {
    skipped.push("learning_patterns");
  }

  // ── Deduplicate against existing goals ──
  const existingTitles = new Set(generatedGoals.map(g => g.title.toLowerCase()));
  const uniqueGoals = newGoals.filter(g => !existingTitles.has(g.title.toLowerCase()));

  // ── Sort by priority * confidence ──
  uniqueGoals.sort((a, b) => (b.priority * b.confidence) - (a.priority * a.confidence));

  // ── Limit ──
  const finalGoals = uniqueGoals.slice(0, MAX_GOALS_PER_CYCLE);

  // ── Store ──
  generatedGoals.push(...finalGoals);
  saveGoals();

  // ── Register with recursiveGoals if available ──
  try {
    const { createMetaGoal } = await import("./recursiveGoals");
    for (const goal of finalGoals) {
      createMetaGoal({
        type: "self_improvement",
        title: goal.title,
        description: goal.description,
        rationale: goal.rationale,
        priority: goal.priority,
        recursive: false,
        subGoals: goal.targetFiles.map(f => ({
          title: `Investigate ${f}`,
          description: `Analyze and fix issues in ${f}`,
          targetFile: f,
        })),
      });
    }
  } catch {
    // recursiveGoals not available
  }

  return {
    goals: finalGoals,
    analysisTime: Date.now() - startTime,
    sourcesAnalyzed,
    skipped,
  };
}

// ─── Goal Management ───────────────────────────────────────────────────────────

export function getGeneratedGoals(): GeneratedGoal[] {
  if (generatedGoals.length === 0) loadGoals();
  return [...generatedGoals];
}

export function approveGoal(goalId: string): boolean {
  const goal = generatedGoals.find(g => g.id === goalId);
  if (goal && goal.status === "proposed") {
    goal.status = "approved";
    saveGoals();
    return true;
  }
  return false;
}

export function rejectGoal(goalId: string): boolean {
  const goal = generatedGoals.find(g => g.id === goalId);
  if (goal && goal.status === "proposed") {
    goal.status = "rejected";
    saveGoals();
    return true;
  }
  return false;
}

// ─── Diagnostics ───────────────────────────────────────────────────────────────

export function getGoalGeneratorStats(): {
  totalGenerated: number;
  proposed: number;
  approved: number;
  completed: number;
  rejected: number;
  lastGenerationTime: number;
} {
  if (generatedGoals.length === 0) loadGoals();
  return {
    totalGenerated: generatedGoals.length,
    proposed: generatedGoals.filter(g => g.status === "proposed").length,
    approved: generatedGoals.filter(g => g.status === "approved").length,
    completed: generatedGoals.filter(g => g.status === "completed").length,
    rejected: generatedGoals.filter(g => g.status === "rejected").length,
    lastGenerationTime,
  };
}
