/**
 * rlaifJudge.ts — Phase 4a: RLAIF Continuous Self-Improvement
 * Andromeda v9.16.2
 *
 * The AI Judge evaluates past interactions and generates its own DPO pairs
 * (chosen vs rejected) without human intervention. This enables continuous
 * unsupervised fine-tuning.
 */
import { getDb } from "./andromedaDb.js";
import { createLogger } from "./logger.js";
import { chatCompletion, getProviderForTier } from "./llmProvider.js";

const log = createLogger("rlaifJudge");

export interface RlaifPair {
  query: string;
  chosen: string;
  rejected: string;
  score: number; // 1-10
  reasoning: string;
}

/**
 * Runs the AI Judge over recent queries to generate synthetic DPO pairs.
 * It uses the 'pro' tier (Claude via OpenRouter) to evaluate and rewrite
 * responses that were originally generated by lower-tier models.
 */
export async function generateRlaifPairs(limit = 10): Promise<RlaifPair[]> {
  const db = getDb();
  
  // Find recent queries that don't have explicit human feedback
  const rows = db.prepare(`
    SELECT DISTINCT query, response
    FROM feedback
    WHERE rating IS NULL
    ORDER BY created_at DESC
    LIMIT ?
  `).all(limit) as Array<{ query: string; response: string }>;

  if (rows.length === 0) {
    log.info("[RLAIF] No unrated queries found for evaluation.");
    return [];
  }

  log.info(`[RLAIF] Judging ${rows.length} recent queries...`);
  const pairs: RlaifPair[] = [];
  const proProvider = getProviderForTier("pro"); // Claude 3.5 Sonnet

  for (const row of rows) {
    try {
      const prompt = `
You are an expert AI Judge. Your task is to evaluate the following response to a user query, and if it is not perfect, provide a superior "chosen" response.

USER QUERY:
${row.query}

ORIGINAL RESPONSE (To be evaluated):
${row.response}

      const MIN_SCORE_FOR_IMPROVEMENT = 9;
      const MAX_SCORE = 10;

      Evaluate the original response on a scale of 1-MAX_SCORE.
If the score is less than MIN_SCORE_FOR_IMPROVEMENT, write a significantly better response.
If the score is MIN_SCORE_FOR_IMPROVEMENT or MAX_SCORE, just output "PERFECT" for the improved response.

Respond EXACTLY in this JSON format:
{
  "score": number,
  "reasoning": "Brief explanation of the score",
  "improved_response": "The better response, or PERFECT"
}
`;

      const result = await chatCompletion(
        [{ role: "user", content: prompt }],
        { 
          providerId: proProvider, 
          maxTokens: 2000, 
          temperature: 0.2,
          toolChoice: "none"
        }
      );

      if (!result.content) continue;

      // Extract JSON from markdown blocks if present
      const jsonMatch = result.content.match(/```json\n([\s\S]*?)\n```/) || 
                        result.content.match(/\{[\s\S]*\}/);
                        
      if (!jsonMatch) continue;

      const parsed = JSON.parse(jsonMatch[1] || jsonMatch[0]) as {
        score: number;
        reasoning: string;
        improved_response: string;
      };

      if (parsed.score < 9 && parsed.improved_response !== "PERFECT") {
        pairs.push({
          query: row.query,
          chosen: parsed.improved_response,
          rejected: row.response,
          score: parsed.score,
          reasoning: parsed.reasoning
        });
        
        // Save the synthetic feedback to the DB so it gets picked up by selfDistillation.ts
        db.prepare(`
          INSERT INTO feedback (session_id, message_id, query, response, rating, comment, module)
          VALUES ('rlaif-synthetic', 'rlaif-' || hex(randomblob(4)), ?, ?, 1, ?, 'rlaif')
        `).run(row.query, parsed.improved_response, `RLAIF Chosen (Score: ${parsed.score}) - ${parsed.reasoning}`);

        db.prepare(`
          INSERT INTO feedback (session_id, message_id, query, response, rating, comment, module)
          VALUES ('rlaif-synthetic', 'rlaif-' || hex(randomblob(4)), ?, ?, -1, ?, 'rlaif')
        `).run(row.query, row.response, `RLAIF Rejected (Score: ${parsed.score})`);
        
        log.info(`[RLAIF] Generated pair for query: "${row.query.substring(0, 30)}..." (Score: ${parsed.score})`);
      }
    } catch (err) {
      log.warn(`[RLAIF] Failed to judge query: ${(err as Error).message}`);
    }
  }

  log.info(`[RLAIF] Generated ${pairs.length} synthetic DPO pairs.`);
  return pairs;
}
