/**
 * selfTestGenerator.ts — Andromeda v5.68 SOTA Safety Architecture
 *
 * Generates behavioral tests for self-modified code to verify that
 * modifications work correctly at runtime, not just at compile time.
 *
 * Complements the TypeScript check (which only catches type errors)
 * with actual behavioral verification.
 */

import * as fs from "fs";
import * as path from "path";
import { fileURLToPath } from "url";
import { chatCompletion } from "./llmProvider.js";

// ── Types ─────────────────────────────────────────────────────────────────────

export type GeneratedTest = {
  testId: string;
  filePath: string;
  functionName: string;
  testCode: string;
  testType: "unit" | "integration" | "smoke";
  expectedOutcome: string;
  generatedAt: number;
};

export type TestRunResult = {
  testId: string;
  passed: boolean;
  output?: string;
  error?: string;
  durationMs: number;
};

// ── Test Storage ──────────────────────────────────────────────────────────────

function getTestStoragePath(): string {
  try {
    const serverDir = path.dirname(fileURLToPath(import.meta.url));
    return path.resolve(serverDir, "..", "data", "generated_tests.json");
  } catch {
    return path.resolve(process.cwd(), "data", "generated_tests.json");
  }
}

function loadTests(): GeneratedTest[] {
  try {
    const p = getTestStoragePath();
    if (!fs.existsSync(p)) return [];
    return JSON.parse(fs.readFileSync(p, "utf8")) as GeneratedTest[];
  } catch {
    return [];
  }
}

function saveTests(tests: GeneratedTest[]): void {
  try {
    const p = getTestStoragePath();
    const dir = path.dirname(p);
    if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
    fs.writeFileSync(p, JSON.stringify(tests, null, 2), "utf8");
  } catch (e) {
    console.error("[SelfTestGenerator] Failed to save tests:", e);
  }
}

// ── Test Generation ───────────────────────────────────────────────────────────

/**
 * Generate smoke tests for a modified file.
 * These are lightweight tests that verify the module loads and exports correctly.
 */
export async function generateSmokeTests(
  filePath: string,
  fileContent: string,
  rationale: string
): Promise<GeneratedTest[]> {
  try {
    // Extract exported function names
    const exportMatches = fileContent.matchAll(/export\s+(?:async\s+)?function\s+(\w+)/g);
    const exportedFunctions = Array.from(exportMatches).map(m => m[1]);

    if (exportedFunctions.length === 0) return [];

    // Generate a smoke test for each exported function
    const tests: GeneratedTest[] = [];
    const timestamp = Date.now();

    for (const funcName of exportedFunctions.slice(0, 5)) { // Limit to 5 functions
      const testId = `smoke_${path.basename(filePath, ".ts")}_${funcName}_${timestamp}`;
      tests.push({
        testId,
        filePath,
        functionName: funcName,
        testCode: generateSmokeTestCode(filePath, funcName),
        testType: "smoke",
        expectedOutcome: `${funcName} should be importable and callable without throwing`,
        generatedAt: timestamp,
      });
    }

    // Store tests
    const existing = loadTests();
    saveTests([...existing, ...tests]);

    return tests;
  } catch (e) {
    console.error("[SelfTestGenerator] Failed to generate smoke tests:", e);
    return [];
  }
}

function generateSmokeTestCode(filePath: string, funcName: string): string {
  const modulePath = filePath.replace(/\\/g, "/").replace(/\.ts$/, ".js");
  return `
// Auto-generated smoke test for ${funcName} in ${path.basename(filePath)}
// Generated by SelfTestGenerator v5.68
import { ${funcName} } from "${modulePath}";

async function runSmokeTest() {
  try {
    // Verify the function is importable
    if (typeof ${funcName} !== "function") {
      throw new Error("${funcName} is not a function — export may be broken");
    }
    console.log("✓ ${funcName} is exported correctly");
    return { passed: true };
  } catch (e) {
    console.error("✗ ${funcName} smoke test failed:", e.message);
    return { passed: false, error: e.message };
  }
}

runSmokeTest().then(r => process.exit(r.passed ? 0 : 1));
`.trim();
}

/**
 * Generate a behavioral test using LLM analysis of the code change.
 * This is a more expensive operation — only run for high-risk modifications.
 */
export async function generateBehavioralTest(
  filePath: string,
  originalContent: string,
  proposedContent: string,
  rationale: string
): Promise<GeneratedTest | null> {
  try {
    const fileName = path.basename(filePath);

    // Find what changed
    const originalLines = originalContent.split("\n");
    const proposedLines = proposedContent.split("\n");
    const changedLineCount = Math.abs(proposedLines.length - originalLines.length) +
      proposedLines.filter((l, i) => l !== originalLines[i]).length;

    if (changedLineCount > 200) {
      // Too large to analyze meaningfully
      return null;
    }

    const prompt = `You are a TypeScript test generator. Given a code change, generate a single focused behavioral test.

File: ${fileName}
Rationale for change: ${rationale}

Changed code (first 50 lines of proposed):
\`\`\`typescript
${proposedLines.slice(0, 50).join("\n")}
\`\`\`

Generate a single TypeScript test function (no imports needed, just the test body) that:
1. Tests the specific behavior described in the rationale
2. Is executable in Node.js
3. Returns { passed: boolean, message: string }

Respond with ONLY the test function body, no explanation.`;

    const response = await chatCompletion([
      { role: "user", content: prompt }
    ], {
      maxTokens: 500,
      temperature: 0.3,
    });

    if (!response?.content) return null;

    const testId = `behavioral_${path.basename(filePath, ".ts")}_${Date.now()}`;
    const test: GeneratedTest = {
      testId,
      filePath,
      functionName: "behavioral_test",
      testCode: response.content,
      testType: "unit",
      expectedOutcome: rationale,
      generatedAt: Date.now(),
    };

    const existing = loadTests();
    saveTests([...existing, test]);

    return test;
  } catch (e) {
    console.error("[SelfTestGenerator] Failed to generate behavioral test:", e);
    return null;
  }
}

/**
 * Get test statistics for the diagnostic dashboard.
 */
export function getTestStats(): {
  totalTests: number;
  testsByType: Record<string, number>;
  recentTests: number;
} {
  const tests = loadTests();
  const recentCutoff = Date.now() - 24 * 3600_000;
  const typeCount: Record<string, number> = {};
  for (const t of tests) {
    typeCount[t.testType] = (typeCount[t.testType] || 0) + 1;
  }
  return {
    totalTests: tests.length,
    testsByType: typeCount,
    recentTests: tests.filter(t => t.generatedAt > recentCutoff).length,
  };
}
