import { describe, it, expect, vi, beforeEach } from "vitest";
import fs from "fs";
import { predictFailure, recordRsiOutcome, initFailurePredictor, getPredictorState } from "./predictiveFailurePrevention.js";
import { checkLlmCache, writeLlmCache, initLlmCache } from "./llmCallCache.js";
import { queueTaskForBatching, getNextBatch, clearBatchQueue } from "./adaptiveBatchScheduler.js";
import { calculateParetoReward, getParetoFrontierSize } from "./paretoRewardShaper.js";
import { scanForAbstractions, initAbstractionEngine } from "./emergentAbstractionEngine.js";
import { recordDocUpdate, synthesizeJsDoc, initDocSynthesizer } from "./autonomousDocSynthesizer.js";

// Mock FS
vi.mock("fs", () => {
  let mockStorage: Record<string, string> = {};
  return {
    default: {
      existsSync: vi.fn((path: string) => !!mockStorage[path]),
      readFileSync: vi.fn((path: string) => {
        if (!mockStorage[path]) throw new Error("File not found");
        return mockStorage[path];
      }),
      writeFileSync: vi.fn((path: string, data: string) => {
        mockStorage[path] = data;
      }),
      appendFileSync: vi.fn((path: string, data: string) => {
        mockStorage[path] = (mockStorage[path] || "") + data;
      }),
      mkdirSync: vi.fn(),
      _reset: () => { mockStorage = {}; }
    }
  };
});

describe("v24 Cognitive Transcendence & LLM Efficiency", () => {
  beforeEach(() => {
    // @ts-ignore
    fs._reset();
  });

  describe("predictiveFailurePrevention", () => {
    it("should predict failure if failure rate > 80% with 3+ attempts", () => {
      initFailurePredictor();
      
      // Train it to fail
      recordRsiOutcome("test.ts", false, false);
      recordRsiOutcome("test.ts", false, false);
      recordRsiOutcome("test.ts", false, false);
      
      expect(predictFailure("test.ts")).toBe(true);
    });

    it("should not predict failure if attempts < 3", () => {
      initFailurePredictor();
      recordRsiOutcome("test2.ts", false, false);
      recordRsiOutcome("test2.ts", false, false);
      
      expect(predictFailure("test2.ts")).toBe(false);
    });
  });

  describe("llmCallCache", () => {
    it("should cache and retrieve deterministic calls", () => {
      initLlmCache();
      writeLlmCache("test prompt", "response A", "system", 0);
      
      const cached = checkLlmCache("test prompt", "system", 0);
      expect(cached).toBe("response A");
    });

    it("should not cache non-deterministic calls", () => {
      initLlmCache();
      writeLlmCache("test prompt", "response B", "system", 0.7);
      
      const cached = checkLlmCache("test prompt", "system", 0.7);
      expect(cached).toBeNull();
    });
  });

  describe("adaptiveBatchScheduler", () => {
    beforeEach(() => clearBatchQueue());

    it("should batch multiple tasks together under token limit", () => {
      queueTaskForBatching("f1.ts", "short context", 1);
      queueTaskForBatching("f2.ts", "short context 2", 1);
      
      const batch = getNextBatch();
      expect(batch?.tasks.length).toBe(2);
    });

    it("should prioritize higher priority tasks", () => {
      queueTaskForBatching("low.ts", "context", 1);
      queueTaskForBatching("high.ts", "context", 10);
      
      const batch = getNextBatch();
      expect(batch?.tasks[0].filePath).toBe("high.ts");
    });
  });

  describe("paretoRewardShaper", () => {
    it("should identify pareto optimal scores", () => {
      const res1 = calculateParetoReward(0.9, 0.9, 0.9, 0.9);
      expect(res1.isParetoOptimal).toBe(true);
      
      // Dominated by res1
      const res2 = calculateParetoReward(0.8, 0.8, 0.8, 0.8);
      expect(res2.isParetoOptimal).toBe(false);
      
      // Not dominated (better performance)
      const res3 = calculateParetoReward(0.8, 0.95, 0.8, 0.8);
      expect(res3.isParetoOptimal).toBe(true);
    });
  });

  describe("emergentAbstractionEngine", () => {
    it("should identify repeated blocks", () => {
      const content = `
        const a = 1;
        const b = 2;
        const c = 3;
        const d = 4;
        const e = 5;
        const f = 6;
      `;
      const patterns = scanForAbstractions("test.ts", content);
      expect(patterns.length).toBeGreaterThan(0);
    });
  });

  describe("autonomousDocSynthesizer", () => {
    it("should append to changelog", () => {
      initDocSynthesizer();
      recordDocUpdate("file.ts", "Fixed a bug");
      
      // @ts-ignore
      expect(fs.appendFileSync).toHaveBeenCalled();
    });

    it("should synthesize basic JSDoc", () => {
      const code = `export function doSomething() {\n  return 1;\n}`;
      const result = synthesizeJsDoc(code);
      expect(result).toContain("/**");
      expect(result).toContain("Autogenerated JSDoc for doSomething");
    });
  });
});
